name: spell-check
on:
  workflow_dispatch:
jobs:
  current:
    runs-on: ubuntu-22.04
    name: spell-check
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "workflowr/workflowr"
      - name: Setup r2u
        run: |
          echo "deb [arch=amd64] https://dirk.eddelbuettel.com/cranapt jammy main" \
            > /etc/apt/sources.list.d/cranapt.list
          apt-get update
        shell: sudo bash {0}
      - name: Install dependencies
        run: |
          apt-get install --yes \
            r-cran-spelling
        shell: sudo bash {0}
      - name: Spell check
        run: |
          library("spelling")
          spell_check_package()
        shell: Rscript {0}
